# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
before_install:
  - sudo apt-get install -y libfftw3-3 libfftw3-dev libnfft3-2 libnfft3-2 libnfft3-dev
  - autoconf
r_packages:
  - covr
  - fftw
  - fftwtools
  - PET
warnings_are_errors: true
sudo: false
cache: packages
os:
 - linux
r:
 - devel
 - release
 - oldrel
 - 3.3
