# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
before_install:
  - sudo apt-get install -y fftw3 fftw3-dev nfft3 nfft3-dev
r_packages:
  - covr
  - fftw
  - fftwtools
warnings_are_errors: true
sudo: false
cache: packages
os:
 - linux
r:
 - devel
 - release
 - oldrel
 - 3.3
